### ISSUE TITLE
wx.getStorageSync  转换出错

### ISSUE THREAD

**Issue by songlfly** [foxitdog/wx2ali#3]
源代码   if (wx.getStorageSync('buyType')=='buy'){}
转换结果   if(my.getStorageSync({key:'buyType')=='group'}){}

源代码   that.setData({ id: options.id, scrollHeight: wx.getStorageSync('scrollHeight')});
转换结果   that.setData({ id: options.id, scrollHeight: my.getStorageSync({key:'scrollHeight')}})

**Comment by foxitdog** [comment]
你好 当前问题已经知晓 也已经进行修正 您可以npm 更新下 wx2ali
